from .context import cnyear

Cnyeardb = cnyear.Cnyeardb
Cnyear = cnyear.Cnyear

cnyeardb_handler = Cnyeardb()
cnyear = Cnyear('清宣統六年')
print(cnyeardb_handler.lkp_dnst('清',r'\b清\b',d1='後金·清'))
print(cnyeardb_handler.lkp_rgnl('清','天聰',da=r'\b清\b'))
print(cnyeardb_handler.lkp_dnst('清',da=r'\b清\b'))
print(cnyeardb_handler.lkp_dnst('清'))
print(cnyeardb_handler.mtch_dnst('三國吳'))
print(cnyeardb_handler.mtch_dnst('南朝宋'))
print(cnyeardb_handler.mtch_dnst('唐'))
print(cnyeardb_handler.mtch_dnst('清'))
print(cnyeardb_handler.mtch_rgnl('清乾隆十二年'))
print(cnyeardb_handler.mtch_rgnl('清十二年'))
print(cnyeardb_handler.mtch_rgnl('明建文元年'))
print(cnyeardb_handler.mtch_rgnl('南明弘光二年'))
print(cnyeardb_handler.lkp_dnst('明'))
print(cnyeardb_handler.lkp_year(1922))
print(cnyeardb_handler.lkp_year(1822))
print(cnyeardb_handler.lkp_year(1522))
print(cnyeardb_handler.lkp_year(1644))

print(Cnyear('清宣統六年').y2cny())
print(Cnyear('明崇禎十八年').y2cny(ldefaultdy=['明','清','南明']))
print(Cnyear('明崇禎十八年').y2cny(ldefaultdy=['明','南明','清'],dig=True))
print(Cnyear('明崇禎十八年').y2cny(ldefaultdy=['明'],dig=True))
print(Cnyear('明崇禎17年').y2cny(ldefaultdy=['明','清']))
print(Cnyear('明崇禎十七年').y2cny(ldefaultdy=['清','明'],dig=True))
print(Cnyear('明崇禎間').y2cny(ldefaultdy=['清','明']))
print(Cnyear('民國間').y2cny(ldefaultdy=['清','明']))
print(Cnyear('民國三十八年').y2cny(ldefaultdy=['清','明']))
print(Cnyear('一九四九年').y2cny(ldefaultdy=['清','明'], dig=True))

def test_cnyear_y2cny(s, ldefaultdy=[], dig=False):
    r = Cnyear(s).y2cny(ldefaultdy=ldefaultdy, dig=dig)
    print(s, r)

test_cnyear_y2cny('民國1年',dig=True)
test_cnyear_y2cny('民國三十九年')
test_cnyear_y2cny('民國三十八年')
test_cnyear_y2cny('民國38年')
test_cnyear_y2cny('1949年')
test_cnyear_y2cny('1948年',dig=True)
test_cnyear_y2cny('一九二三年')
test_cnyear_y2cny('清宣統十八年')
test_cnyear_y2cny('明崇禎十七年')
test_cnyear_y2cny('清順治2年',dig=True)
test_cnyear_y2cny('明崇禎二十八年',ldefaultdy=['明','清','南明'])
test_cnyear_y2cny('明崇禎二十八年',ldefaultdy=['明','南明','清'])
test_cnyear_y2cny('明崇禎二十八年',ldefaultdy=['明'])
test_cnyear_y2cny('清宣統四十一年',ldefaultdy=['明'],dig=True)
test_cnyear_y2cny('明宣統四十一年',ldefaultdy=['明'])
test_cnyear_y2cny('民國上年',ldefaultdy=['明'])

print('\n')
x = Cnyear('明崇禎二十八年')
print(x.get_year_realkind())
print(x.y2cny(ldefaultdy=['南明']))
print(x.y2cny(ldefaultdy=['清']))
print(x.get_year_realkind())

print(Cnyear('清雍正二年').get_year_component())
print(Cnyear('清光緒十八年').get_year_component())
print(Cnyear('民國元年').get_year_component())
print(Cnyear('1892年').get_year_component())

print(Cnyear('清雍正二年').get_year_offset())
print(Cnyear('清光緒十八年').get_year_offset())
print(Cnyear('清光緒三十八年').get_year_offset(dig=True))
print(Cnyear('民國元年').get_year_offset())
print(Cnyear('民國元年').get_year_offset(dig=True))
print(Cnyear('民國元年').get_year_offset(dig=True,conv_1=True))
print(Cnyear('1892年').get_year_offset())
print(Cnyear('一九零三年').get_year_offset())
print(Cnyear('一九三〇年').get_year_offset(dig=True))
print(Cnyear('清康熙間').get_year_offset(dig=True))
print(Cnyear('民國間').get_year_offset(dig=True))

print(Cnyear('清雍正間abcdefg').cnyear_raw)
print(Cnyear('清雍正八年13232').cnyear_raw)
print(Cnyear('清雍正8年13232').cnyear_raw)
print(Cnyear('民國元年13232').cnyear_raw)
print(Cnyear('民國25年13232').cnyear_raw)
print(Cnyear('1825年13232').cnyear_raw)
print(Cnyear('二零二五年13232').cnyear_raw)

print(Cnyear('明崇禎元年9999').get_year_raw())
print(Cnyear('明崇禎1年9999').get_year_raw())
print(Cnyear('清乾隆間九月二十八日9999').get_year_raw())
print(Cnyear('1995年9999abcdefg').get_year_raw())
print(Cnyear('民國1年年9999abcdefg').get_year_raw())
print(Cnyear('abcdefg民國間9999abcdefg').get_year_raw())

